################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

[package]
authors = ["Daniel Krippner <dk.mailbox@gmx.net>"]
categories = ["api-bindings"]
description = "Rust implementation of the Eclipse uProtocol SDK"
documentation = "https://github.com/eclipse-uprotocol/uprotocol-spec#readme"
edition = "2021"
exclude = [
    "tests/*",
    "tools/*",
    ".devcontainer/*",
    ".vscode/*",
    ".github/*",
    ".gitignore",
]
keywords = ["uProtocol", "SDK"]
license = "Apache-2.0"
name = "uprotocol-sdk"
readme = "README.md"
repository = "https://github.com/eclipse-uprotocol/uprotocol-rust"
rust-version = "1.66"
version = "0.1.5"

[dependencies]
async-trait = "0.1"
byteorder = "1.4"
bytes = "1.4"
chrono = "0.4"
cloudevents-sdk = { version = "0.7" }
mac_address = "1.1"
mime = "0.3"
prost = "0.12"
prost-types = "0.12"
rand = "0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2"
uuid = { version = "1.4", features = ["v6", "v8"] }

[build-dependencies]
prost-build = { version = "0.12" }
protoc-bin-vendored = { version = "3" }
ureq = "2.7"

[dev-dependencies]
base64 = "0.21"
test-case = "3.3"
